name: 🧪 Tests
on:
    pull_request:
    push:
        branches: ["main", "master", "develop", "release"]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.8", "3.9", "3.10"]
        name: 🧪 Run tests
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Install Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"
            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
            - name: Run tests
              run: |
                  poetry install --group dev
                  tox -e test
